/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rmcar' at '2016-10-23 21:04' with Gradle 3.0
 *
 * @author rmcar, @date 2016-10-23 21:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
